apiVersion: v1
kind: ConfigMap
metadata:
  name: kutahyalilar-config
  namespace: kutahyalilar
data:
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  JWT_ALGORITHM: "HS256"
  JWT_EXPIRE_MINUTES: "60"
  AUTH_DB_NAME: "auth_db"
  USER_DB_NAME: "user_db"
  TRIP_DB_NAME: "trip_db"
  BOOKING_DB_NAME: "booking_db"
  PAYMENT_DB_NAME: "payment_db"
  SMTP_HOST: "mailhog"
  SMTP_PORT: "1025"
  SMTP_FROM: "no-reply@kutahyalilar.com"
  TRIP_SERVICE_HOST: "trip-service"
  PAYMENT_SERVICE_HOST: "payment-service"
