apiVersion: v1
kind: Secret
metadata:
  name: kutahyalilar-secrets
  namespace: kutahyalilar
type: Opaque
stringData:
  POSTGRES_USER: "kutahyalilar"
  POSTGRES_PASSWORD: "supersecret"
  JWT_SECRET_KEY: "change-me-in-production"
